import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    // Landing View
    "hero_title": "Online SMS Hub",
    "hero_desc": "Connect with friends, manage your contacts, and receive automated updates on Jokes, Sports, and News directly to your mobile.",
    "feat_chat_title": "Chat and Message friends",
    "feat_chat_desc": "Send unlimited free messages to any registered user in your friend list.",
    "feat_sms_title": "SMS to Non-Friends",
    "feat_sms_desc": "Allowing 5 free SMS messages per phone number to connect instantly with unregistered users.",
    "feat_paid_title": "Paid SMS Services",
    "feat_paid_desc": "Activate premium daily updates for Sports scores, News alerts, Current affairs, or Jokes.",
    "demo_login": "Demo Quick Log In",
    "select_preseed": "Select pre-seeded account...",
    "already_registered": "Already registered?",
    "dont_have_account": "Don't have an account?",
    "login": "Log In",
    "signup": "Sign Up",
    "username": "Username",
    "password": "Password",
    "confirm_password": "Confirm Password",
    "fullname": "Full Name",
    "email": "Email ID",
    "mobile_number": "Mobile Number (10 digits)",
    "verification_code": "Verification Code",
    "enter_code": "Enter code",
    "create_account": "Create Account",
    "two_factor_title": "Two-Factor Authentication (2FA)",
    "two_factor_desc": "Please enter the 6-digit OTP code sent to your email.",
    "otp_code": "OTP Code",
    "enter_otp": "Enter 6-digit code (e.g. 123456)",
    "verify_and_login": "Verify & Log In",
    "back_to_login": "Back to Log In",
    "username_available": "Username is available!",
    "username_taken": "Username is already taken.",
    "checking_availability": "Checking availability...",

    // Sidebar
    "sms_workspace": "SMS Workspace",
    "logout": "Log Out",
    "logged_in_as": "Logged In As",
    "tab_chats": "Chats",
    "tab_contacts": "Contacts",
    "tab_requests": "Requests",
    "tab_services": "Services",
    "tab_templates": "Templates",
    "tab_groups": "Groups",
    "tab_stats": "Stats",
    "tab_security": "Security",
    "tab_profile": "Profile",
    "tab_settings": "Settings",
    "search_placeholder": "Search friends by name/mobile...",
    "searching": "Searching...",
    "no_matching_users": "No matching users found.",
    "loading_more": "Loading more...",
    "no_active_chats": "No active chats. Add contacts to begin messaging.",
    "friend_no_msg": "Friend (No messages)",
    "contact_no_msg": "Contact (No messages)",
    "free_badge": "Free",
    "free_limit_badge": "Free 5/5",
    "empty_contacts": "Your contact list is empty.",
    "add_contact": "+ Add New Contact",
    "btn_delete": "Delete",
    "btn_chat": "Chat",
    "content_open": "Content is open in the main panel.",
    "status_friend": "Friend",
    "status_sent": "Request Sent",
    "status_received": "Friend Request",

    // Chat Window
    "select_chat_placeholder": "Select a chat from the sidebar or go to the Contacts tab to start a new thread.",
    "welcome_message": "Welcome to SMS Chat System",
    "character_limit": "characters remaining",
    "send_button": "Send",
    "sending": "Sending...",
    "draft_sms_ai": "Draft SMS using AI",
    "ai_assistant": "AI Assistant",
    "select_tone": "Select tone...",
    "tone_formal": "Formal",
    "tone_funny": "Funny",
    "tone_polite": "Polite",
    "tone_intimate": "Intimate",
    "generate": "Generate",
    "prompt_placeholder": "e.g., Ask Bob if we are still meeting at 5 PM tomorrow...",
    "quota_status": "Quota status: free messages remaining for this contact.",
    "unlimited_chat": "Unlimited free chat (friends).",
    "not_friends_status": "You are not friends. You can send up to 5 free messages to this number.",
    "add_friend_btn": "Add Friend to chat unlimited",
    "sent_friend_req": "⏳ Friend request sent",
    "is_typing": "is typing...",

    // Modals
    "create_new_contact": "Create New Contact",
    "first_name": "First Name",
    "last_name": "Last Name",
    "mobile_number_label": "Mobile Number (10 digits)",
    "btn_cancel": "Cancel",
    "btn_save_contact": "Save Contact",
    "subscribe_premium": "Subscribe to premium services",
    "credit_card": "CREDIT CARD",
    "card_holder": "Card Holder",
    "expires": "Expires",
    "billed_amount": "Billed Amount",
    "enter_otp_payment": "Enter payment OTP code",
    "enter_6_digit_otp": "Enter 6-digit OTP code",
    "check_console": "* Please check backend console for transaction OTP code.",
    "card_number": "Credit Card Number",
    "card_expiry": "Expiry Date (MM/YY)",
    "cvv": "CVV (3 digits)",
    "payment_notice": "Charges will be billed to your credit card immediately.",
    "pay_and_activate": "Pay & Activate",

    // Settings Tab
    "settings_title": "Settings",
    "settings_desc": "Configure your account settings and application preferences.",
    "language_settings": "Language Settings",
    "select_language": "Select System Language",
    "future_settings": "Future Preferences (Coming Soon)",
    "theme_mode": "Theme Mode",
    "theme_mode_desc": "Toggle between light, dark or glassmorphism interfaces.",
    "push_notifications": "Push Notifications",
    "push_notifications_desc": "Receive notification sounds and system alerts for incoming messages.",
    "auto_delete": "Auto-Delete Chats",
    "auto_delete_desc": "Automatically clear chat history older than 30 days.",
    "save_settings": "Save Settings",
    "settings_saved": "Settings saved successfully!",

    // AI Chatbot
    "ai_chatbot_title": "🤖 AI Chatbot Assistant",
    "ask_anything": "Ask me anything! 💬",
    "ai_typing": "AI Assistant is typing a reply...",
    "input_question": "Type a question...",

    // Profile Tab
    "edit_profile": "Edit Profile",
    "edit_profile_desc": "Customize your personal and professional profile details.",
    "personal_details": "Personal Details",
    "gender": "Gender",
    "dob": "Date of Birth",
    "marital_status": "Marital Status",
    "address": "Address",
    "hobbies": "Hobbies",
    "sports": "Sports",
    "likes": "Likes",
    "dislikes": "Dislikes",
    "cuisines": "Preferred Cuisines",
    "professional_details": "Professional Details",
    "qualification": "Qualification",
    "work_status": "Work Status",
    "school_name": "School Name",
    "college_name": "College Name",
    "company_name": "Company / Organization",
    "designation": "Designation",
    "reset_changes": "Reset Changes",
    "save_profile": "Save Profile",

    // Security Tab
    "security_settings": "Security Settings",
    "security_desc": "Manage your two-factor authentication, privacy, and blocklist settings.",
    "two_factor_auth": "Two-Factor Authentication",
    "two_factor_toggle_desc": "Require an OTP code sent to your email when logging in to your account.",
    "sms_privacy": "SMS Privacy Control",
    "sms_privacy_toggle_desc": "Reject messages from unknown numbers (strangers cannot send you 5 free messages).",
    "stranger_block": " strangers cannot send 5 free messages to you.",
    "blocklist_title": "Manage Blocklist",
    "block_number": "Block Number",
    "enter_block_number": "Enter 10-digit number to block",
    "btn_block": "Block",
    "blocklist_empty": "Your blocklist is empty.",
    "unblock": "Unblock",

    // Services Tab
    "premium_services": "Premium SMS Services",
    "services_desc": "Subscribe to automated SMS services. Receive daily updates tailored to your interests.",
    "activated": "Activated",
    "active": "Active",
    "subscribe": "Subscribe",
    "price_per_month": "month",
    "jokes_service": "Jokes Service",
    "jokes_desc": "Receive a hilarious daily joke to brighten up your day.",
    "current_affairs_service": "Current Affairs",
    "current_affairs_desc": "Stay informed with key local and global political updates.",
    "sports_service": "Sports Service",
    "sports_desc": "Receive instant live match results, sports news, and league standings.",
    "news_service": "News Service",
    "news_desc": "Get breaking news notifications and daily headlines.",

    // Requests Tab
    "friend_requests": "Friend Requests",
    "requests_desc": "Manage your pending incoming and outgoing connection requests.",
    "incoming_requests": "Incoming Requests",
    "no_incoming_requests": "No incoming friend requests.",
    "accept": "Accept",
    "decline": "Decline",
    "outgoing_requests": "Outgoing Requests",
    "no_outgoing_requests": "No outgoing friend requests.",
    "send_friend_request": "Send Friend Request",
    "recipient_email": "Recipient's Email Address",
    "send": "Send Request",

    // Templates Tab
    "sms_templates": "SMS Templates",
    "templates_desc": "Create and manage quick template snippets for quick messaging.",
    "create_template": "Create New Template",
    "template_title": "Template Title",
    "template_body": "Template Body",
    "save_template": "Save Template",
    "no_templates": "No custom templates found. Create one above!",

    // Groups Tab
    "contact_groups": "Contact Groups",
    "groups_desc": "Group your contacts together to send bulk SMS announcements easily.",
    "create_group": "Create New Group",
    "group_name": "Group Name",
    "save_group": "Save Group",
    "no_groups": "No groups created yet.",
    "members_in_group": "Members in",
    "add_member_to_group": "Add Member",
    "select_contact_to_add": "Select contact to add...",
    "add_btn": "Add",
    "bulk_sms_title": "Send Bulk SMS to Group",
    "message_body": "Message Body",
    "send_bulk_btn": "Send Bulk SMS",
    "bulk_logs_title": "Bulk SMS Transaction Log",

    // Analytics Tab
    "analytics_dashboard": "Analytics Dashboard",
    "analytics_desc": "Track your messaging volumes, statistics, and billing transactions.",
    "total_sms_sent": "Total SMS Sent",
    "free_sms_sent": "Free SMS Sent",
    "paid_sms_sent": "Paid SMS Sent",
    "active_services": "Active Services",
    "transaction_history": "Transaction Billing History",
    "no_transactions": "No billing transactions found.",
    "amount": "Amount",
    "date": "Date",
    "status": "Status",
    "service_name": "Service Name",

    // Validation/Alerts
    "cannot_block_self": "Cannot block your own mobile number.",
    "blocked_success": "Number blocked successfully.",
    "unblocked_success": "Number unblocked successfully.",
    "contact_added_success": "Contact created successfully.",
    "contact_deleted_success": "Contact deleted successfully.",
    "friend_req_sent_success": "Friend request sent successfully.",
    "friend_req_respond_success": "Friend request updated.",
    "group_created_success": "Group created successfully.",
    "group_deleted_success": "Group deleted successfully.",
    "member_added_success": "Member added to group.",
    "member_removed_success": "Member removed from group.",
    "template_created_success": "Template created successfully.",
    "template_deleted_success": "Template deleted successfully.",
    "payment_otp_requested": "Payment verification OTP code sent. Please check backend console.",
    "service_activated_success": "Service activated successfully!",
    "profile_saved_success": "Profile details updated successfully.",
    "confirm_delete_contact": "Are you sure you want to delete contact",
    "confirm_delete_group": "Are you sure you want to delete this group? All membership info will be deleted.",
    "confirm_delete_template": "Are you sure you want to delete this template?",
  },
  vi: {
    // Landing View
    "hero_title": "Hệ thống Quản lý SMS",
    "hero_desc": "Kết nối với bạn bè, quản lý danh bạ và nhận thông tin cập nhật tự động về Truyện cười, Thể thao và Tin tức trực tiếp đến điện thoại của bạn.",
    "feat_chat_title": "Trò chuyện với bạn bè",
    "feat_chat_desc": "Gửi tin nhắn miễn phí không giới hạn cho bất kỳ người dùng đã đăng ký nào trong danh sách bạn bè.",
    "feat_sms_title": "SMS cho người lạ",
    "feat_sms_desc": "Cho phép gửi 5 tin nhắn SMS miễn phí cho mỗi số điện thoại để kết nối ngay với người dùng chưa đăng ký.",
    "feat_paid_title": "Dịch vụ SMS trả phí",
    "feat_paid_desc": "Kích hoạt nhận bản tin cao cấp hàng ngày về Thể thao, Tin tức, Thời sự hoặc Truyện cười.",
    "demo_login": "Đăng nhập nhanh (Bản Demo)",
    "select_preseed": "Chọn tài khoản có sẵn...",
    "already_registered": "Đã có tài khoản?",
    "dont_have_account": "Chưa có tài khoản?",
    "login": "Đăng Nhập",
    "signup": "Đăng Ký",
    "username": "Tên đăng nhập",
    "password": "Mật khẩu",
    "confirm_password": "Xác nhận mật khẩu",
    "fullname": "Họ và Tên",
    "email": "Địa chỉ Email",
    "mobile_number": "Số điện thoại (10 chữ số)",
    "verification_code": "Mã xác nhận Captcha",
    "enter_code": "Nhập mã Captcha",
    "create_account": "Đăng Ký Tài Khoản",
    "two_factor_title": "Xác thực 2 lớp (2FA)",
    "two_factor_desc": "Vui lòng nhập mã OTP gồm 6 chữ số đã được gửi tới email của bạn.",
    "otp_code": "Mã OTP xác thực",
    "enter_otp": "Nhập mã 6 số (ví dụ: 123456)",
    "verify_and_login": "Xác minh & Đăng nhập",
    "back_to_login": "Quay lại đăng nhập",
    "username_available": "Tên đăng nhập hợp lệ!",
    "username_taken": "Tên đăng nhập đã tồn tại.",
    "checking_availability": "Đang kiểm tra...",

    // Sidebar
    "sms_workspace": "SMS Workspace",
    "logout": "Đăng Xuất",
    "logged_in_as": "Đang đăng nhập dưới tên",
    "tab_chats": "Tin nhắn",
    "tab_contacts": "Danh bạ",
    "tab_requests": "Kết bạn",
    "tab_services": "Dịch vụ",
    "tab_templates": "Mẫu tin",
    "tab_groups": "Nhóm số",
    "tab_stats": "Thống kê",
    "tab_security": "Bảo mật",
    "tab_profile": "Cá nhân",
    "tab_settings": "Cài đặt",
    "search_placeholder": "Tìm bạn bè bằng tên/SĐT...",
    "searching": "Đang tìm kiếm...",
    "no_matching_users": "Không tìm thấy người dùng phù hợp.",
    "loading_more": "Đang tải thêm...",
    "no_active_chats": "Chưa có cuộc trò chuyện nào. Hãy thêm liên hệ để bắt đầu nhắn tin.",
    "friend_no_msg": "Bạn bè (Chưa nhắn tin)",
    "contact_no_msg": "Danh bạ (Chưa nhắn tin)",
    "free_badge": "Miễn phí",
    "free_limit_badge": "Miễn phí 5/5",
    "empty_contacts": "Danh bạ của bạn hiện đang trống.",
    "add_contact": "+ Thêm liên hệ mới",
    "btn_delete": "Xóa",
    "btn_chat": "Nhắn tin",
    "content_open": "Nội dung đang được hiển thị ở bảng chính.",
    "status_friend": "Bạn bè",
    "status_sent": "Đã gửi lời mời",
    "status_received": "Lời mời kết bạn",

    // Chat Window
    "select_chat_placeholder": "Chọn một cuộc trò chuyện từ thanh bên hoặc truy cập tab Danh bạ để bắt đầu.",
    "welcome_message": "Chào mừng đến với hệ thống SMS",
    "character_limit": "ký tự còn lại",
    "send_button": "Gửi",
    "sending": "Đang gửi...",
    "draft_sms_ai": "Soạn tin nhắn bằng AI",
    "ai_assistant": "Trợ lý AI",
    "select_tone": "Chọn văn phong...",
    "tone_formal": "Trang trọng",
    "tone_funny": "Hài hước",
    "tone_polite": "Lịch sự",
    "tone_intimate": "Thân mật",
    "generate": "Biên soạn",
    "prompt_placeholder": "Ví dụ: Hỏi Nam xem ngày mai 5h chiều có họp như lịch không...",
    "quota_status": "Trạng thái hạn ngạch: còn lại tin nhắn miễn phí cho số này.",
    "unlimited_chat": "Trò chuyện miễn phí không giới hạn (Bạn bè).",
    "not_friends_status": "Hai người chưa là bạn bè. Bạn có thể gửi tối đa 5 tin nhắn miễn phí đến số này.",
    "add_friend_btn": "Gửi lời mời kết bạn để nhắn tin không giới hạn",
    "sent_friend_req": "⏳ Đã gửi lời mời kết bạn",
    "is_typing": "đang nhập tin nhắn...",

    // Modals
    "create_new_contact": "Tạo liên hệ mới",
    "first_name": "Tên",
    "last_name": "Họ",
    "mobile_number_label": "Số điện thoại (10 số)",
    "btn_cancel": "Hủy bỏ",
    "btn_save_contact": "Lưu liên hệ",
    "subscribe_premium": "Đăng ký các dịch vụ cao cấp",
    "credit_card": "THẺ TÍN DỤNG",
    "card_holder": "Chủ sở hữu thẻ",
    "expires": "Hết hạn",
    "billed_amount": "Số tiền thanh toán",
    "enter_otp_payment": "Nhập mã OTP Xác thực thanh toán",
    "enter_6_digit_otp": "Nhập mã OTP 6 số",
    "check_console": "* Vui lòng kiểm tra Console backend để lấy mã OTP giao dịch.",
    "card_number": "Số thẻ tín dụng",
    "card_expiry": "Ngày hết hạn (MM/YY)",
    "cvv": "Mã CVV (3 chữ số)",
    "payment_notice": "Số tiền dịch vụ sẽ được tính vào thẻ của bạn ngay lập tức.",
    "pay_and_activate": "Thanh toán & Kích hoạt",

    // Settings Tab
    "settings_title": "Cài đặt hệ thống",
    "settings_desc": "Thay đổi cài đặt tài khoản và thiết lập các tùy chọn ứng dụng của bạn.",
    "language_settings": "Thiết lập ngôn ngữ",
    "select_language": "Chọn ngôn ngữ hiển thị",
    "future_settings": "Tùy chọn khác (Tính năng đang phát triển)",
    "theme_mode": "Giao diện hiển thị",
    "theme_mode_desc": "Thay đổi giao diện sáng, tối hoặc giao diện kính mờ (glassmorphism).",
    "push_notifications": "Thông báo ứng dụng",
    "push_notifications_desc": "Bật âm thanh báo tin nhắn và thông báo trên màn hình khi có tin nhắn mới.",
    "auto_delete": "Tự động dọn dẹp tin nhắn",
    "auto_delete_desc": "Tự động xóa lịch sử cuộc trò chuyện đã cũ hơn 30 ngày.",
    "save_settings": "Lưu cài đặt",
    "settings_saved": "Cài đặt ngôn ngữ hiển thị đã được cập nhật thành công!",

    // AI Chatbot
    "ai_chatbot_title": "🤖 Trợ lý AI Chatbot",
    "ask_anything": "Hỏi mình bất cứ điều gì nhé! 💬",
    "ai_typing": "Trợ lý AI đang soạn câu trả lời...",
    "input_question": "Nhập câu hỏi...",

    // Profile Tab
    "edit_profile": "Cập nhật cá nhân",
    "edit_profile_desc": "Tùy chỉnh thông tin chi tiết và hồ sơ nghề nghiệp của bạn.",
    "personal_details": "Thông tin cá nhân",
    "gender": "Giới tính",
    "dob": "Ngày sinh",
    "marital_status": "Tình trạng hôn nhân",
    "address": "Địa chỉ",
    "hobbies": "Sở thích",
    "sports": "Thể thao",
    "likes": "Thích",
    "dislikes": "Ghét",
    "cuisines": "Ẩm thực ưa thích",
    "professional_details": "Thông tin công việc",
    "qualification": "Bằng cấp",
    "work_status": "Trạng thái công việc",
    "school_name": "Tên trường (Phổ thông)",
    "college_name": "Tên trường (Đại học/Cao đẳng)",
    "company_name": "Công ty / Tổ chức",
    "designation": "Chức vụ",
    "reset_changes": "Khôi phục thay đổi",
    "save_profile": "Lưu thông tin",

    // Security Tab
    "security_settings": "Thiết lập bảo mật",
    "security_desc": "Quản lý xác thực 2 lớp (2FA), cài đặt quyền riêng tư và danh sách chặn.",
    "two_factor_auth": "Xác thực 2 lớp (2FA)",
    "two_factor_toggle_desc": "Yêu cầu mã OTP gửi qua Email khi đăng nhập tài khoản.",
    "sms_privacy": "Chặn tin nhắn từ người lạ",
    "sms_privacy_toggle_desc": "Từ chối nhận tin nhắn từ những số lạ (người lạ không thể gửi 5 tin nhắn miễn phí cho bạn).",
    "stranger_block": " người lạ không thể nhắn tin miễn phí cho bạn.",
    "blocklist_title": "Danh sách chặn số điện thoại",
    "block_number": "Chặn số mới",
    "enter_block_number": "Nhập số điện thoại 10 chữ số để chặn",
    "btn_block": "Chặn số",
    "blocklist_empty": "Danh sách chặn hiện đang trống.",
    "unblock": "Bỏ chặn",

    // Services Tab
    "premium_services": "Các dịch vụ SMS trả phí",
    "services_desc": "Đăng ký dịch vụ SMS tự động hàng ngày gửi trực tiếp về điện thoại.",
    "activated": "Đã kích hoạt",
    "active": "Đang hoạt động",
    "subscribe": "Đăng ký nhận",
    "price_per_month": "tháng",
    "jokes_service": "Dịch vụ kể chuyện cười",
    "jokes_desc": "Nhận một mẩu truyện cười dí dỏm mỗi ngày giúp tinh thần thoải mái.",
    "current_affairs_service": "Bản tin Thời sự tổng hợp",
    "current_affairs_desc": "Luôn cập nhật thông tin chính trị thời sự trong nước và quốc tế.",
    "sports_service": "Thông tin Thể thao",
    "sports_desc": "Nhận nhanh tỷ số trận đấu trực tiếp, tin tức thể thao và bảng xếp hạng.",
    "news_service": "Cập nhật Tin tức mới",
    "news_desc": "Đọc tin nóng hổi và tiêu điểm báo chí gửi trực tiếp mỗi ngày.",

    // Requests Tab
    "friend_requests": "Lời mời kết bạn",
    "requests_desc": "Quản lý các lời mời kết bạn gửi đến và gửi đi của bạn.",
    "incoming_requests": "Lời mời đã nhận",
    "no_incoming_requests": "Không có lời mời kết bạn nào gửi đến.",
    "accept": "Đồng ý",
    "decline": "Từ chối",
    "outgoing_requests": "Lời mời đã gửi",
    "no_outgoing_requests": "Không có lời mời kết bạn nào đang gửi đi.",
    "send_friend_request": "Gửi lời mời kết bạn mới",
    "recipient_email": "Nhập địa chỉ Email của người muốn kết bạn",
    "send": "Gửi yêu cầu",

    // Templates Tab
    "sms_templates": "Tin nhắn mẫu",
    "templates_desc": "Tạo và quản lý các đoạn tin nhắn mẫu để gửi đi nhanh chóng.",
    "create_template": "Tạo mẫu tin mới",
    "template_title": "Tiêu đề mẫu tin",
    "template_body": "Nội dung mẫu tin",
    "save_template": "Lưu mẫu tin",
    "no_templates": "Chưa có tin nhắn mẫu nào được tạo. Hãy tạo mới ở trên!",

    // Groups Tab
    "contact_groups": "Nhóm số liên hệ",
    "groups_desc": "Gộp nhiều liên hệ vào nhóm để gửi thông báo tin nhắn hàng loạt nhanh chóng.",
    "create_group": "Tạo nhóm liên hệ mới",
    "group_name": "Tên nhóm liên hệ",
    "save_group": "Lưu nhóm liên hệ",
    "no_groups": "Chưa có nhóm liên hệ nào được tạo.",
    "members_in_group": "Thành viên thuộc nhóm",
    "add_member_to_group": "Thêm thành viên",
    "select_contact_to_add": "Chọn số liên hệ để thêm...",
    "add_btn": "Thêm số",
    "bulk_sms_title": "Gửi SMS hàng loạt cho nhóm",
    "message_body": "Nội dung tin nhắn",
    "send_bulk_btn": "Gửi tin hàng loạt",
    "bulk_logs_title": "Lịch sử gửi tin hàng loạt",

    // Analytics Tab
    "analytics_dashboard": "Thống kê & Lịch sử",
    "analytics_desc": "Theo dõi số lượng tin nhắn đã gửi, số dư tài khoản và hóa đơn dịch vụ.",
    "total_sms_sent": "Tổng tin nhắn đã gửi",
    "free_sms_sent": "Tin nhắn miễn phí",
    "paid_sms_sent": "Tin nhắn tính phí",
    "active_services": "Dịch vụ đang nhận",
    "transaction_history": "Lịch sử thanh toán giao dịch",
    "no_transactions": "Không tìm thấy lịch sử giao dịch thanh toán nào.",
    "amount": "Số tiền",
    "date": "Ngày thanh toán",
    "status": "Trạng thái",
    "service_name": "Tên dịch vụ",

    // Validation/Alerts
    "cannot_block_self": "Không thể chặn số điện thoại của chính bạn.",
    "blocked_success": "Đã chặn số điện thoại thành công.",
    "unblocked_success": "Đã bỏ chặn số điện thoại thành công.",
    "contact_added_success": "Tạo liên hệ thành công.",
    "contact_deleted_success": "Xóa liên hệ thành công.",
    "friend_req_sent_success": "Gửi lời mời kết bạn thành công.",
    "friend_req_respond_success": "Đã cập nhật phản hồi kết bạn.",
    "group_created_success": "Tạo nhóm liên hệ thành công.",
    "group_deleted_success": "Xóa nhóm liên hệ thành công.",
    "member_added_success": "Đã thêm thành viên vào nhóm.",
    "member_removed_success": "Đã xóa thành viên khỏi nhóm.",
    "template_created_success": "Tạo mẫu tin nhắn thành công.",
    "template_deleted_success": "Xóa mẫu tin nhắn thành công.",
    "payment_otp_requested": "Đã gửi mã OTP xác thực thanh toán. Vui lòng kiểm tra Console backend.",
    "service_activated_success": "Kích hoạt dịch vụ thành công!",
    "profile_saved_success": "Thông tin cá nhân đã được lưu thành công.",
    "confirm_delete_contact": "Bạn có chắc chắn muốn xóa liên hệ",
    "confirm_delete_group": "Bạn có chắc chắn muốn xóa nhóm này? Toàn bộ thành viên sẽ bị xóa khỏi nhóm.",
    "confirm_delete_template": "Bạn có chắc chắn muốn xóa tin nhắn mẫu này không?",
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  const setLanguage = (lang) => {
    localStorage.setItem('language', lang);
    setLanguageState(lang);
  };

  const t = (key) => {
    if (!translations[language]) return key;
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
